from flask import Flask, render_template, request, jsonify, send_file
from datetime import datetime
import json
import os
from io import BytesIO
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer
from reportlab.pdfgen import canvas

app = Flask(__name__)

# Class details
CLASS_DETAILS = "BSCS (C) - FALL 2024"

# Student data
STUDENTS = [
    {"name": "Abdul Rehaman", "roll": "003."},
    {"name": "Abdullah Saboor", "roll": "006."},
    {"name": "Ahmed Abbas", "roll": "009."},
    {"name": "Abdullah Tausif", "roll": "012."},
    {"name": "Aimen Saeed", "roll": "015."},
    {"name": "Aryan Ali", "roll": "021."},
    {"name": "Bisma Aslam", "roll": "027."},
    {"name": "Hamna Bukhari", "roll": "039."},
    {"name": "Hassan Muhammad", "roll": "042."},
    {"name": "Hunain Khan", "roll": "045."},
    {"name": "Maham Ul Akhtar ", "roll": "048."},
    {"name": "Mehak Fatima", "roll": "051."},
    {"name": "Minahil Shahid", "roll": "054."},
    {"name": "M Abdullah Shahbaz", "roll": "060."},
    {"name": "Muhammad Awais", "roll": "063."},
    {"name": "Muhammad Hashir", "roll": "069."},
    {"name": "Muhammad Mustajab Ul Haq", "roll": "075."},
    {"name": "Muhammad Usman Bilal", "roll": "084."},
    {"name": "Muhammad Zain ", "roll": "087."},
    {"name": "Rafay Rasheed", "roll": "093."},
    {"name": "Rimal Atif", "roll": "096."},
    {"name": "Samir Afzal ", "roll": "099."},
    {"name": "Shahbaz Mehndi", "roll": "102."},
    {"name": "Muhammad Mehdi Raza", "roll": "105."},
    {"name": "Taha Abdullah", "roll": "108."},
    {"name": "Usman Ibrahim", "roll": "111."},
    {"name": "Zainab Faisal", "roll": "114."},
    {"name": "Syed Muhammad Ahmad", "roll": "120."},
    {"name": "AbduL Moiz Asif", "roll": "123."},
    {"name": "Ayesha Amjad", "roll": "126."},
    {"name": "Muhammad Mutahhar Mudassar", "roll": "129."},
    {"name": "Yassir Hussain", "roll": "132."},
    {"name": "Eman Fatima ", "roll": "135."},
    {"name": "Abdul Rehman", "roll": "140."},
    {"name": "Duaa E Zahra", "roll": "144."},
    {"name": "Ibrahim Khalid", "roll": "147."},
    {"name": "Muhamamd Usman Siddiqui", "roll": "150."},
    {"name": "ShanzAe Mudassar", "roll": "153."},
    {"name": "Zainab Irfan", "roll": "156."},
    {"name": "Saad Ahmed", "roll": "158."},
    {"name": "Abdul Manan", "roll": "170."},
]

@app.route('/')
def index():
    return render_template('index.html', students=STUDENTS, class_details=CLASS_DETAILS)

@app.route('/api/students')
def get_students():
    return jsonify(STUDENTS)

@app.route('/api/generate-pdf', methods=['POST'])
def generate_pdf():
    data = request.json
    date = data.get('date')
    class_name = data.get('className')
    attendance = data.get('attendance', {})
    
    # Create PDF in memory
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter)
    elements = []
    styles = getSampleStyleSheet()
    
    # Title
    title_text = f"{CLASS_DETAILS}"
    title = Paragraph(title_text, styles['Title'])
    elements.append(title)
    elements.append(Spacer(1, 12))
    
    # Header
    header_text = f"{date} - {class_name} Attendance"
    header = Paragraph(header_text, styles['Heading2'])
    elements.append(header)
    elements.append(Spacer(1, 12))
    
    # Create table data
    table_data = [['Roll No.', 'Status', 'Name']]
    present_count = 0
    absent_count = 0
    
    for student in STUDENTS:
        roll = student['roll']
        status = attendance.get(roll, 'Not Marked')
        name = student['name']
        
        if status == 'P':
            present_count += 1
        elif status == 'A':
            absent_count += 1
            
        table_data.append([roll, status, name])
    
    # Create table
    table = Table(table_data)
    table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.grey),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, 0), 12),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
        ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
        ('GRID', (0, 0), (-1, -1), 1, colors.black)
    ]))
    
    elements.append(table)
    elements.append(Spacer(1, 12))
    
    # Summary
    summary_text = f"""
    Total Students: {len(STUDENTS)}<br/>
    Present Students: {present_count}<br/>
    Absent Students: {absent_count}
    """
    summary = Paragraph(summary_text, styles['Normal'])
    elements.append(summary)
    elements.append(Spacer(1, 12))
    
    # Footer
    footer_text = "Generated by Attendance Management System v2.0 (Web) - Modified by Mutahhar Mudassar"
    footer = Paragraph(footer_text, styles['Italic'])
    elements.append(footer)
    
    # Build PDF
    doc.build(elements)
    buffer.seek(0)
    
    filename = f"{date}_{class_name}_Attendance.pdf"
    
    return send_file(
        buffer,
        as_attachment=True,
        download_name=filename,
        mimetype='application/pdf'
    )

@app.route('/api/summary', methods=['POST'])
def get_summary():
    data = request.json
    attendance = data.get('attendance', {})
    
    present_count = sum(1 for status in attendance.values() if status == 'P')
    absent_count = sum(1 for status in attendance.values() if status == 'A')
    not_marked = len(STUDENTS) - present_count - absent_count
    
    return jsonify({
        'total': len(STUDENTS),
        'present': present_count,
        'absent': absent_count,
        'notMarked': not_marked
    })

if __name__ == '__main__':
    import os
    port = int(os.environ.get('PORT', 5000))
    app.run(debug=False, host='0.0.0.0', port=port)
